# GitHub action to build

name: Build

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pnpm install
      - run: pnpm run check-lint
      - run: pnpm run check-format
      - run: pnpm run test
      - run: pnpm run build-ci
